# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :ci_test do

    # We make sure the app compiles
    gradle(
        task: "assemble",
        build_type: "Debug"
    )

    # Then run the unit tests
    gradle(
      task: "test",
      build_type: "DebugUnitTest"
    )

    gradle(
      task: "api:test",
    )
  end

  desc "Submit a build to Google Play, in the internal lane"
  lane :release do

    #gradleProperties = {
    #    versionCode: 2920001,
    #    googleMapsApiKey: ENV['GOOGLE_MAPS_API_KEY'],
    #    keystoreFilePath: '../private/timeforcoffee.jks',
    #    keystoreKeyAlias: ENV['PLAYSTORE_KEY_ALIAS'],
    #    keystoreKeyPass:  ENV['PLAYSTORE_KEY_PASS'],
    #    keystoreStorePass: ENV['PLAYSTORE_STORE_PASS']
    #}
    
    ## build and release mobile app
    #gradle(
    #    task: ":mobile:bundle",
    #    properties: gradleProperties
    #)
    #
    #supply(
    #    track: 'internal',
    #    aab: 'mobile/build/outputs/bundle/release/mobile-release.aab'
    #)

    # build and release wear app
     gradleProperties = {
        versionCode: 2920002, 
        googleMapsApiKey: ENV['GOOGLE_MAPS_API_KEY'],
        keystoreFilePath: '../private/timeforcoffee.jks',
        keystoreKeyAlias: ENV['PLAYSTORE_KEY_ALIAS'],
        keystoreKeyPass:  ENV['PLAYSTORE_KEY_PASS'],
        keystoreStorePass: ENV['PLAYSTORE_STORE_PASS']
    }

    gradle(
        task: ":wear:bundle",
        properties: gradleProperties
    )

    supply(
        track: 'internal',
        aab: 'wear/build/outputs/bundle/release/wear-release.aab'
    )
  end
end
