# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :ci_test do

    # We make sure the app compiles
    gradle(
        task: "assemble",
        flavor: "Full",
        build_type: "Debug"
    )

    # Then run the unit tests
    gradle(
      task: "test",
      flavor: "Full",
      build_type: "DebugUnitTest"
    )

    gradle(
      task: "api:test",
    )
  end

  desc "Submit a build to Google Play, in the internal lane"
  lane :release do

    gradleProperties = {
        versionCode: 255321 + $env.GITHUB_RUN_NUMBER, #255321 is the last build number used on GitlabCI
        googleMapsApiKey: $secrets.GOOGLE_MAPS_API_KEY
        keystoreFilePath: 'files/timeforcoffee.jks',
        keystoreKeyAlias: $secrets.PLAYSTORE_KEY_ALIAS
        keystoreKeyPass:  $secrets.PLAYSTORE_KEY_PASS
        keystoreStorePass: $secrets.PLAYSTORE_STORE_PASS
    }
    
    gradle(
        task: "assemble",
        flavor: "Full",
        build_type: "Release",
        properties: gradleProperties
    )

    supply(
        track: 'internal',
        apk: 'mobile/build/outputs/apk/full/release/mobile-full-release.apk'
    )
  end
end
