name: Test and deploy

on:
  push:

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
      - run: bundle install

      - name: Unit tests
        run: bundle exec fastlane ci_test
